name: Bug Report
description: Found a bug? Report it here.
labels: [ bug ]
body:
- type: textarea
  attributes:
    label: Bug Description
    description: "A clear and concise description of what the issue is."
  validations:
    required: true
- type: textarea
  attributes:
    label: Reproduction steps
    description: "How do you trigger this bug?"
  validations:
    required: true
- type: checkboxes
  attributes:
    label: Before submitting a bug report
    options:
    - label: This bug wasn't already reported (I have searched bug reports on GitHub).
      required: true
