name: Bug Report
description: Found a bug? Report it here.
labels: ["Bug"]
body:
- type: textarea
  attributes:
    label: Bug Description
    description: "What is the bug?"
    render: bash
  validations:
    required: true
- type: textarea
  attributes:
    label: Reproduction steps
    description: "How do you trigger this bug? Please walk us through it step by step."
    value: |
      1.
      2.
      3.
      ...
    render: bash
  validations:
    required: true
- type: checkboxes
  attributes:
    options:
    - label: This bug hasn''t been reported yet.
      required: true
