name: New AntiCheat
description: Found an anticheat not on the list? Request it to be added here.
labels: "new anticheat"
body:
- type: input
  attributes:
    label: Anticheat Name
    description: "What is the Anticheat's name?"
  validations:
    required: true
- type: input
  attributes:
    label: Cost
    description: "How much does the anticheat cost and in what currency? (for example, $19.99 USD)"
  validations:
    required: true
- type: dropdown
  attributes:
    label: Platform(s)
    description: "What platform(s) does the anticheat support?"
    multiple: true
    options:
      - Bukkit (Java)
      - Sponge (Java)
      - Fabric (Java)
      - Forge (Java)
      - MineStom (Java)
      - Skript (Java)
      - Datapack (Java)
      - Nukkit (Bedrock)
      - Behavior Pack (Bedrock)
      - PocketMine (Bedrock)
      - Unknown
      - Other
  validations:
    required: true
- type: dropdown
  attributes:
    label: Status
    description: "What is the anticheat's development status?"
    multiple: false
    options:
      - Active (Recent updates)
      - Old (Has not been updated recently, about 4 months)
      - Inactive (Author has stated work will be slow)
      - Unmaintained (Author has stated it is not currently being worked on, but may be in the future)
      - Discontinued (Author has stated it will not be worked on)
      - Unavailable (No working official links to the Anticheat)
      - Unknown
  validations:
    required: true
- type: input
  attributes:
    label: Minecraft Versions
    description: "What Minecraft versions does the anticheat support? (Unknown is an option) (PLEASE DO NOT PUT ANTICHEAT VERSION)"
  validations:
    required: true
- type: textarea
  attributes:
    label: Links
    description: 'What official links can be used to obtain the anticheat? (if possible, do not use direct download links) ("None" is valid)'
  validations:
    required: true
- type: input
  attributes:
    label: Rating Percentage and number of ratings
    description: "If any platforms show ratings, what is the anticheat's rating as a percentage, and how many ratings does it have? (for example, 100%, 20 ratings) If on SpigotMC, this can be skipped."
  validations:
    required: false
- type: checkboxes
  attributes:
    label: Before submitting an anticheat
    options:
    - label: This anticheat wasn't already submitted (I have searched anticheat submitions on GitHub).
      required: true
