name: New AntiCheat
description: Found a new anticheat? ask me to add it here.
labels: "new anticheat"
body:
- type: input
  attributes:
    label: Anticheat Name
    description: "What is the anticheat called?"
  validations:
    required: true
- type: dropdown
  attributes:
    label: Cost
    description: "Is the anticheat free or premium (paid)?"
    multiple: false
    options:
      - Free
      - Premium
  validations:
    required: true
- type: dropdown
  attributes:
    label: Edition
    description: "Is the anticheat for Java, or Bedrock?"
    multiple: false
    options:
      - Java
      - Bedrock
      - Unknown
  validations:
    required: true
- type: dropdown
  attributes:
    label: Platform
    description: "What platform is the anticheat on?"
    multiple: false
    options:
      - Bukkit
      - Fabric
      - Forge
      - Nukkit
      - Behavior Pack
      - Skript
      - PocketMine
      - Unknown
      - Other (explain in "Other explanation")
  validations:
    required: true
- type: dropdown
  attributes:
    label: Status
    description: "What is the anticheat's current status?"
    multiple: false
    options:
      - Active (Recent updates, not explicitly inactive/unmaintained/discontinued)
      - Inactive (Author has stated work on the project will be slow)
      - Unmaintained (Explicitly unmaintained, not discontinued, but is not currently being worked on)
      - Discontinued (Explicitly Discontinued, not being worked on)
      - Unknown
      - Unavailable (No working official links to the anticheat)
      - Old (Has not been updated recently, and does not fit into any other category)
  validations:
    required: true
- type: input
  attributes:
    label: Minecraft Versions
    description: "What Minecraft versions does the anticheat support (if discontinued, use last supported versions)? (Unknown is an option) (DO NOT ANTICHEAT VERSION)"
  validations:
    required: true
- type: textarea
  attributes:
    label: Links
    description: 'What official links can be used to obtain the anticheat? (Do not use direct download links) (None or Unknown is valid, if the selected Status is "Unavailable")'
  validations:
    required: true
- type: input
  attributes:
    label: Rating Percentage and number of ratings
    description: "What is the anticheats rating as a percentage? Please also include the amount of ratings received."
  validations:
    required: false
- type: textarea
  attributes:
    label: Other explanation
    description: 'This question is for if you selected "Other" in a question'
  validations:
    required: false
- type: checkboxes
  attributes:
    label: Before submitting an anticheat
    options:
    - label: This anticheat wasn't already submitted (I have searched anticheat submitions on GitHub).
      required: true
