name: Suggestion
description: Suggest a new feature, or change.
labels: [ enhancement ]
body:
- type: textarea
  attributes:
    label: Description
    description: "A clear and concise description of what the suggestion is."
  validations:
    required: true
- type: checkboxes
  attributes:
    label: Before submitting a suggestion
    options:
    - label: This wasn't already suggested (I have searched suggestions on GitHub).
      required: true
