name: Suggestion
description: Suggest a new feature, or change.
labels: ["Enhancement"]
body:
- type: textarea
  attributes:
    label: Bug Description
    description: "A clear and concise description of what the feature/change is."
    render: yml
  validations:
    required: true
- type: checkboxes
  attributes:
    label: Before submitting a bug report
    options:
    - label: This wasn't already suggested (I have searched suggestions on GitHub).
      required: true
